/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainSupplyAgreementsRouteImport } from './routes/_main/supply-agreements'
import { Route as MainSuppliersRouteImport } from './routes/_main/suppliers'
import { Route as MainStoresRouteImport } from './routes/_main/stores'
import { Route as MainProductsRouteImport } from './routes/_main/products'
import { Route as MainSalesIndexRouteImport } from './routes/_main/sales/index'
import { Route as MainPurchasesIndexRouteImport } from './routes/_main/purchases/index'
import { Route as MainInventoryIndexRouteImport } from './routes/_main/inventory/index'
import { Route as MainSalesRegisterRouteImport } from './routes/_main/sales/register'
import { Route as MainPurchasesRegisterRouteImport } from './routes/_main/purchases/register'
import { Route as MainInventoryShrinkageRouteImport } from './routes/_main/inventory/shrinkage'
import { Route as MainInventoryRestockRouteImport } from './routes/_main/inventory/restock'
import { Route as MainInventoryMovementsRouteImport } from './routes/_main/inventory/movements'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainSupplyAgreementsRoute = MainSupplyAgreementsRouteImport.update({
  id: '/supply-agreements',
  path: '/supply-agreements',
  getParentRoute: () => MainRoute,
} as any)
const MainSuppliersRoute = MainSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => MainRoute,
} as any)
const MainStoresRoute = MainStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => MainRoute,
} as any)
const MainProductsRoute = MainProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => MainRoute,
} as any)
const MainSalesIndexRoute = MainSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => MainRoute,
} as any)
const MainPurchasesIndexRoute = MainPurchasesIndexRouteImport.update({
  id: '/purchases/',
  path: '/purchases/',
  getParentRoute: () => MainRoute,
} as any)
const MainInventoryIndexRoute = MainInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => MainRoute,
} as any)
const MainSalesRegisterRoute = MainSalesRegisterRouteImport.update({
  id: '/sales/register',
  path: '/sales/register',
  getParentRoute: () => MainRoute,
} as any)
const MainPurchasesRegisterRoute = MainPurchasesRegisterRouteImport.update({
  id: '/purchases/register',
  path: '/purchases/register',
  getParentRoute: () => MainRoute,
} as any)
const MainInventoryShrinkageRoute = MainInventoryShrinkageRouteImport.update({
  id: '/inventory/shrinkage',
  path: '/inventory/shrinkage',
  getParentRoute: () => MainRoute,
} as any)
const MainInventoryRestockRoute = MainInventoryRestockRouteImport.update({
  id: '/inventory/restock',
  path: '/inventory/restock',
  getParentRoute: () => MainRoute,
} as any)
const MainInventoryMovementsRoute = MainInventoryMovementsRouteImport.update({
  id: '/inventory/movements',
  path: '/inventory/movements',
  getParentRoute: () => MainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/products': typeof MainProductsRoute
  '/stores': typeof MainStoresRoute
  '/suppliers': typeof MainSuppliersRoute
  '/supply-agreements': typeof MainSupplyAgreementsRoute
  '/inventory/movements': typeof MainInventoryMovementsRoute
  '/inventory/restock': typeof MainInventoryRestockRoute
  '/inventory/shrinkage': typeof MainInventoryShrinkageRoute
  '/purchases/register': typeof MainPurchasesRegisterRoute
  '/sales/register': typeof MainSalesRegisterRoute
  '/inventory/': typeof MainInventoryIndexRoute
  '/purchases/': typeof MainPurchasesIndexRoute
  '/sales/': typeof MainSalesIndexRoute
}
export interface FileRoutesByTo {
  '/products': typeof MainProductsRoute
  '/stores': typeof MainStoresRoute
  '/suppliers': typeof MainSuppliersRoute
  '/supply-agreements': typeof MainSupplyAgreementsRoute
  '/': typeof MainIndexRoute
  '/inventory/movements': typeof MainInventoryMovementsRoute
  '/inventory/restock': typeof MainInventoryRestockRoute
  '/inventory/shrinkage': typeof MainInventoryShrinkageRoute
  '/purchases/register': typeof MainPurchasesRegisterRoute
  '/sales/register': typeof MainSalesRegisterRoute
  '/inventory': typeof MainInventoryIndexRoute
  '/purchases': typeof MainPurchasesIndexRoute
  '/sales': typeof MainSalesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/_main/products': typeof MainProductsRoute
  '/_main/stores': typeof MainStoresRoute
  '/_main/suppliers': typeof MainSuppliersRoute
  '/_main/supply-agreements': typeof MainSupplyAgreementsRoute
  '/_main/': typeof MainIndexRoute
  '/_main/inventory/movements': typeof MainInventoryMovementsRoute
  '/_main/inventory/restock': typeof MainInventoryRestockRoute
  '/_main/inventory/shrinkage': typeof MainInventoryShrinkageRoute
  '/_main/purchases/register': typeof MainPurchasesRegisterRoute
  '/_main/sales/register': typeof MainSalesRegisterRoute
  '/_main/inventory/': typeof MainInventoryIndexRoute
  '/_main/purchases/': typeof MainPurchasesIndexRoute
  '/_main/sales/': typeof MainSalesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/products'
    | '/stores'
    | '/suppliers'
    | '/supply-agreements'
    | '/inventory/movements'
    | '/inventory/restock'
    | '/inventory/shrinkage'
    | '/purchases/register'
    | '/sales/register'
    | '/inventory/'
    | '/purchases/'
    | '/sales/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/products'
    | '/stores'
    | '/suppliers'
    | '/supply-agreements'
    | '/'
    | '/inventory/movements'
    | '/inventory/restock'
    | '/inventory/shrinkage'
    | '/purchases/register'
    | '/sales/register'
    | '/inventory'
    | '/purchases'
    | '/sales'
  id:
    | '__root__'
    | '/_main'
    | '/_main/products'
    | '/_main/stores'
    | '/_main/suppliers'
    | '/_main/supply-agreements'
    | '/_main/'
    | '/_main/inventory/movements'
    | '/_main/inventory/restock'
    | '/_main/inventory/shrinkage'
    | '/_main/purchases/register'
    | '/_main/sales/register'
    | '/_main/inventory/'
    | '/_main/purchases/'
    | '/_main/sales/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/supply-agreements': {
      id: '/_main/supply-agreements'
      path: '/supply-agreements'
      fullPath: '/supply-agreements'
      preLoaderRoute: typeof MainSupplyAgreementsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/suppliers': {
      id: '/_main/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof MainSuppliersRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/stores': {
      id: '/_main/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof MainStoresRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/products': {
      id: '/_main/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof MainProductsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/sales/': {
      id: '/_main/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof MainSalesIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/purchases/': {
      id: '/_main/purchases/'
      path: '/purchases'
      fullPath: '/purchases/'
      preLoaderRoute: typeof MainPurchasesIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/inventory/': {
      id: '/_main/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof MainInventoryIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/sales/register': {
      id: '/_main/sales/register'
      path: '/sales/register'
      fullPath: '/sales/register'
      preLoaderRoute: typeof MainSalesRegisterRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/purchases/register': {
      id: '/_main/purchases/register'
      path: '/purchases/register'
      fullPath: '/purchases/register'
      preLoaderRoute: typeof MainPurchasesRegisterRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/inventory/shrinkage': {
      id: '/_main/inventory/shrinkage'
      path: '/inventory/shrinkage'
      fullPath: '/inventory/shrinkage'
      preLoaderRoute: typeof MainInventoryShrinkageRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/inventory/restock': {
      id: '/_main/inventory/restock'
      path: '/inventory/restock'
      fullPath: '/inventory/restock'
      preLoaderRoute: typeof MainInventoryRestockRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/inventory/movements': {
      id: '/_main/inventory/movements'
      path: '/inventory/movements'
      fullPath: '/inventory/movements'
      preLoaderRoute: typeof MainInventoryMovementsRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainRouteChildren {
  MainProductsRoute: typeof MainProductsRoute
  MainStoresRoute: typeof MainStoresRoute
  MainSuppliersRoute: typeof MainSuppliersRoute
  MainSupplyAgreementsRoute: typeof MainSupplyAgreementsRoute
  MainIndexRoute: typeof MainIndexRoute
  MainInventoryMovementsRoute: typeof MainInventoryMovementsRoute
  MainInventoryRestockRoute: typeof MainInventoryRestockRoute
  MainInventoryShrinkageRoute: typeof MainInventoryShrinkageRoute
  MainPurchasesRegisterRoute: typeof MainPurchasesRegisterRoute
  MainSalesRegisterRoute: typeof MainSalesRegisterRoute
  MainInventoryIndexRoute: typeof MainInventoryIndexRoute
  MainPurchasesIndexRoute: typeof MainPurchasesIndexRoute
  MainSalesIndexRoute: typeof MainSalesIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainProductsRoute: MainProductsRoute,
  MainStoresRoute: MainStoresRoute,
  MainSuppliersRoute: MainSuppliersRoute,
  MainSupplyAgreementsRoute: MainSupplyAgreementsRoute,
  MainIndexRoute: MainIndexRoute,
  MainInventoryMovementsRoute: MainInventoryMovementsRoute,
  MainInventoryRestockRoute: MainInventoryRestockRoute,
  MainInventoryShrinkageRoute: MainInventoryShrinkageRoute,
  MainPurchasesRegisterRoute: MainPurchasesRegisterRoute,
  MainSalesRegisterRoute: MainSalesRegisterRoute,
  MainInventoryIndexRoute: MainInventoryIndexRoute,
  MainPurchasesIndexRoute: MainPurchasesIndexRoute,
  MainSalesIndexRoute: MainSalesIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
