/**
 * Auto-generated TypeScript bindings for Tauri commands
 * Generated by tauri-typegen v0.5.1
 * Generated at: 2026-06-16T17:06:14.653520031+00:00
 * Generator: zod
 *
 * Do not edit manually - regenerate using: cargo tauri-typegen generate
 */

import { invoke } from '@tauri-apps/api/core';
import { ZodError } from 'zod';
import * as types from './types';

export interface CommandHooks<T> {
  /** Called when Zod schema validation fails */
  onValidationError?: (error: ZodError) => void;

  /** Called when Tauri invoke fails (Rust error, serialization, etc.) */
  onInvokeError?: (error: unknown) => void;

  /** Called when command succeeds */
  onSuccess?: (result: T) => void;

  /** Called after command settles (success or error) */
  onSettled?: () => void;
}

export async function createInventory(params: types.CreateInventoryParams, hooks?: CommandHooks<types.Inventory>): Promise<types.Inventory> {
  try {
    const result = types.CreateInventoryParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.Inventory>('create_inventory', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function createProduct(params: types.CreateProductParams, hooks?: CommandHooks<types.Product>): Promise<types.Product> {
  try {
    const result = types.CreateProductParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.Product>('create_product', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function createStore(params: types.CreateStoreParams, hooks?: CommandHooks<types.Store>): Promise<types.Store> {
  try {
    const result = types.CreateStoreParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.Store>('create_store', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function createSupplier(params: types.CreateSupplierParams, hooks?: CommandHooks<types.Supplier>): Promise<types.Supplier> {
  try {
    const result = types.CreateSupplierParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.Supplier>('create_supplier', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function createSupplyAgreement(params: types.CreateSupplyAgreementParams, hooks?: CommandHooks<types.SupplyAgreement>): Promise<types.SupplyAgreement> {
  try {
    const result = types.CreateSupplyAgreementParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.SupplyAgreement>('create_supply_agreement', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function deleteInventory(params: types.DeleteInventoryParams, hooks?: CommandHooks<void>): Promise<void> {
  try {
    const result = types.DeleteInventoryParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<void>('delete_inventory', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function deleteProduct(params: types.DeleteProductParams, hooks?: CommandHooks<void>): Promise<void> {
  try {
    const result = types.DeleteProductParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<void>('delete_product', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function deleteStore(params: types.DeleteStoreParams, hooks?: CommandHooks<void>): Promise<void> {
  try {
    const result = types.DeleteStoreParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<void>('delete_store', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function deleteSupplier(params: types.DeleteSupplierParams, hooks?: CommandHooks<void>): Promise<void> {
  try {
    const result = types.DeleteSupplierParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<void>('delete_supplier', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function deleteSupplyAgreement(params: types.DeleteSupplyAgreementParams, hooks?: CommandHooks<void>): Promise<void> {
  try {
    const result = types.DeleteSupplyAgreementParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<void>('delete_supply_agreement', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function findPurchaseById(params: types.FindPurchaseByIdParams, hooks?: CommandHooks<types.Purchase>): Promise<types.Purchase> {
  try {
    const result = types.FindPurchaseByIdParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.Purchase>('find_purchase_by_id', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function findSaleById(params: types.FindSaleByIdParams, hooks?: CommandHooks<types.Sale>): Promise<types.Sale> {
  try {
    const result = types.FindSaleByIdParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.Sale>('find_sale_by_id', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function getDashboardData(params: types.GetDashboardDataParams, hooks?: CommandHooks<types.DashboardData>): Promise<types.DashboardData> {
  try {
    const result = types.GetDashboardDataParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.DashboardData>('get_dashboard_data', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function getInventorySummary(params: types.GetInventorySummaryParams, hooks?: CommandHooks<types.InventorySummaryOutput>): Promise<types.InventorySummaryOutput> {
  try {
    const result = types.GetInventorySummaryParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.InventorySummaryOutput>('get_inventory_summary', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function getSalesByPaymentMethod(params: types.GetSalesByPaymentMethodParams, hooks?: CommandHooks<types.PaymentMethodSalesOutput[]>): Promise<types.PaymentMethodSalesOutput[]> {
  try {
    const result = types.GetSalesByPaymentMethodParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.PaymentMethodSalesOutput[]>('get_sales_by_payment_method', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function getSalesByStore(params: types.GetSalesByStoreParams, hooks?: CommandHooks<types.StoreSalesOutput[]>): Promise<types.StoreSalesOutput[]> {
  try {
    const result = types.GetSalesByStoreParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.StoreSalesOutput[]>('get_sales_by_store', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function getSalesOverTime(params: types.GetSalesOverTimeParams, hooks?: CommandHooks<types.DailySalesOutput[]>): Promise<types.DailySalesOutput[]> {
  try {
    const result = types.GetSalesOverTimeParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.DailySalesOutput[]>('get_sales_over_time', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function getTopProducts(params: types.GetTopProductsParams, hooks?: CommandHooks<types.TopProductOutput[]>): Promise<types.TopProductOutput[]> {
  try {
    const result = types.GetTopProductsParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.TopProductOutput[]>('get_top_products', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function registerPurchaseOperation(params: types.RegisterPurchaseOperationParams, hooks?: CommandHooks<types.PurchaseOperationOutput>): Promise<types.PurchaseOperationOutput> {
  try {
    const result = types.RegisterPurchaseOperationParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.PurchaseOperationOutput>('register_purchase_operation', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function registerRestockMovement(params: types.RegisterRestockMovementParams, hooks?: CommandHooks<types.InventoryMovementOutput>): Promise<types.InventoryMovementOutput> {
  try {
    const result = types.RegisterRestockMovementParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.InventoryMovementOutput>('register_restock_movement', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function registerSaleOperation(params: types.RegisterSaleOperationParams, hooks?: CommandHooks<types.SaleOperationOutput>): Promise<types.SaleOperationOutput> {
  try {
    const result = types.RegisterSaleOperationParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.SaleOperationOutput>('register_sale_operation', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function registerShrinkageMovement(params: types.RegisterShrinkageMovementParams, hooks?: CommandHooks<types.InventoryMovementOutput>): Promise<types.InventoryMovementOutput> {
  try {
    const result = types.RegisterShrinkageMovementParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.InventoryMovementOutput>('register_shrinkage_movement', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function searchInventories(params: types.SearchInventoriesParams, hooks?: CommandHooks<types.PaginatedResult<Inventory>>): Promise<types.PaginatedResult<Inventory>> {
  try {
    const result = types.SearchInventoriesParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.PaginatedResult<Inventory>>('search_inventories', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function searchProducts(params: types.SearchProductsParams, hooks?: CommandHooks<types.PaginatedResult<Product>>): Promise<types.PaginatedResult<Product>> {
  try {
    const result = types.SearchProductsParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.PaginatedResult<Product>>('search_products', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function searchPurchases(params: types.SearchPurchasesParams, hooks?: CommandHooks<types.PaginatedResult<Purchase>>): Promise<types.PaginatedResult<Purchase>> {
  try {
    const result = types.SearchPurchasesParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.PaginatedResult<Purchase>>('search_purchases', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function searchSales(params: types.SearchSalesParams, hooks?: CommandHooks<types.PaginatedResult<Sale>>): Promise<types.PaginatedResult<Sale>> {
  try {
    const result = types.SearchSalesParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.PaginatedResult<Sale>>('search_sales', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function searchStores(params: types.SearchStoresParams, hooks?: CommandHooks<types.PaginatedResult<Store>>): Promise<types.PaginatedResult<Store>> {
  try {
    const result = types.SearchStoresParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.PaginatedResult<Store>>('search_stores', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function searchSuppliers(params: types.SearchSuppliersParams, hooks?: CommandHooks<types.PaginatedResult<Supplier>>): Promise<types.PaginatedResult<Supplier>> {
  try {
    const result = types.SearchSuppliersParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.PaginatedResult<Supplier>>('search_suppliers', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function searchSupplyAgreements(params: types.SearchSupplyAgreementsParams, hooks?: CommandHooks<types.PaginatedResult<SupplyAgreement>>): Promise<types.PaginatedResult<SupplyAgreement>> {
  try {
    const result = types.SearchSupplyAgreementsParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.PaginatedResult<SupplyAgreement>>('search_supply_agreements', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function updateInventory(params: types.UpdateInventoryParams, hooks?: CommandHooks<types.Inventory>): Promise<types.Inventory> {
  try {
    const result = types.UpdateInventoryParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.Inventory>('update_inventory', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function updateProduct(params: types.UpdateProductParams, hooks?: CommandHooks<types.Product>): Promise<types.Product> {
  try {
    const result = types.UpdateProductParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.Product>('update_product', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function updateStore(params: types.UpdateStoreParams, hooks?: CommandHooks<types.Store>): Promise<types.Store> {
  try {
    const result = types.UpdateStoreParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.Store>('update_store', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function updateSupplier(params: types.UpdateSupplierParams, hooks?: CommandHooks<types.Supplier>): Promise<types.Supplier> {
  try {
    const result = types.UpdateSupplierParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.Supplier>('update_supplier', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function updateSupplyAgreement(params: types.UpdateSupplyAgreementParams, hooks?: CommandHooks<types.SupplyAgreement>): Promise<types.SupplyAgreement> {
  try {
    const result = types.UpdateSupplyAgreementParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.SupplyAgreement>('update_supply_agreement', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}
