/**
 * Auto-generated TypeScript bindings for Tauri commands
 * Generated by tauri-typegen v0.5.1
 * Generated at: 2026-06-16T17:06:14.652656764+00:00
 * Generator: zod
 *
 * Do not edit manually - regenerate using: cargo tauri-typegen generate
 */

import { z } from 'zod';

export const TextValueSchema = z.object({
  value: z.string(),
  max_length: z.coerce.number(),
});

export type TextValue = z.infer<typeof TextValueSchema>;
export const CodeSchema = z.object({
  value: TextValueSchema,
});

export type Code = z.infer<typeof CodeSchema>;
export const CreateInventoryInputSchema = z.object({
  inventoryCode: z.string().min(1, { message: "Inventory code must be between 1 and 20 characters" }).max(20, { message: "Inventory code must be between 1 and 20 characters" }),
  storeId: z.string(),
  productId: z.string(),
  quantity: z.coerce.number(),
  priceLocal: z.string(),
  minStock: z.coerce.number(),
  status: z.string().min(1, { message: "Status cannot be empty" }),
  active: z.coerce.boolean(),
});

export type CreateInventoryInput = z.infer<typeof CreateInventoryInputSchema>;
export const CreateProductInputSchema = z.object({
  productCode: z.string().min(1, { message: "Product code must be between 1 and 20 characters" }).max(20, { message: "Product code must be between 1 and 20 characters" }),
  name: z.string().min(1, { message: "Name must be between 1 and 100 characters" }).max(100, { message: "Name must be between 1 and 100 characters" }),
  initialPrice: z.string(),
  active: z.coerce.boolean(),
});

export type CreateProductInput = z.infer<typeof CreateProductInputSchema>;
export const CreateStoreInputSchema = z.object({
  storeCode: z.string().min(1, { message: "Store code must be between 1 and 20 characters" }).max(20, { message: "Store code must be between 1 and 20 characters" }),
  name: z.string().min(1, { message: "Name must be between 1 and 100 characters" }).max(100, { message: "Name must be between 1 and 100 characters" }),
  address: z.string().min(1, { message: "Address cannot be empty" }),
  phone: z.string().min(7, { message: "Phone number length is invalid" }).max(20, { message: "Phone number length is invalid" }).optional(),
  active: z.coerce.boolean(),
});

export type CreateStoreInput = z.infer<typeof CreateStoreInputSchema>;
export const CreateSupplierInputSchema = z.object({
  name: z.string().min(1, { message: "Name must be between 1 and 100 characters" }).max(100, { message: "Name must be between 1 and 100 characters" }),
  supplierCode: z.string().min(1, { message: "Supplier code must be between 1 and 20 characters" }).max(20, { message: "Supplier code must be between 1 and 20 characters" }),
  contactName: z.string().min(1, { message: "Contact name cannot be empty" }).optional(),
  phone: z.string().min(7, { message: "Phone number length is invalid" }).max(20, { message: "Phone number length is invalid" }).optional(),
  address: z.string().min(1, { message: "Address cannot be empty" }).optional(),
  active: z.coerce.boolean(),
});

export type CreateSupplierInput = z.infer<typeof CreateSupplierInputSchema>;
export const CreateSupplyAgreementInputSchema = z.object({
  productId: z.string(),
  supplierId: z.string(),
  cost: z.string().optional(),
  active: z.coerce.boolean(),
});

export type CreateSupplyAgreementInput = z.infer<typeof CreateSupplyAgreementInputSchema>;
export const OperatorSchema = z.enum(["Eq", "Ne", "Gt", "Gte", "Lt", "Lte", "Like", "Ilike", "In"]);

export type Operator = z.infer<typeof OperatorSchema>;
export const FilterItemInputSchema = z.object({
  field: z.string().min(1, { message: "Filter field cannot be empty" }),
  operator: OperatorSchema,
  value: z.custom<unknown>((val) => true),
});

export type FilterItemInput = z.infer<typeof FilterItemInputSchema>;
export const PaginationInputSchema = z.object({
  page: z.coerce.number().min(1, { message: "Page must be at least 1" }),
  size: z.coerce.number().min(1, { message: "Size must be between 1 and 100" }).max(100, { message: "Size must be between 1 and 100" }),
});

export type PaginationInput = z.infer<typeof PaginationInputSchema>;
export const SortOrderSchema = z.enum(["Asc", "Desc"]);

export type SortOrder = z.infer<typeof SortOrderSchema>;
export const SortInputSchema = z.object({
  field: z.string().min(1, { message: "Sort field cannot be empty" }),
  order: SortOrderSchema,
});

export type SortInput = z.infer<typeof SortInputSchema>;
export const CriteriaInputSchema = z.object({
  pagination: PaginationInputSchema.optional(),
  filters: z.array(FilterItemInputSchema).optional(),
  globalFilter: z.array(FilterItemInputSchema).optional(),
  sort: z.array(SortInputSchema).optional(),
});

export type CriteriaInput = z.infer<typeof CriteriaInputSchema>;
export const DailySalesOutputSchema = z.object({
  date: z.string(),
  total: z.string(),
  count: z.coerce.number(),
});

export type DailySalesOutput = z.infer<typeof DailySalesOutputSchema>;
export const InventorySummaryOutputSchema = z.object({
  totalProducts: z.coerce.number(),
  lowStock: z.coerce.number(),
  outOfStock: z.coerce.number(),
  totalValue: z.string(),
});

export type InventorySummaryOutput = z.infer<typeof InventorySummaryOutputSchema>;
export const PaymentMethodSalesOutputSchema = z.object({
  method: z.string(),
  totalRevenue: z.string(),
  count: z.coerce.number(),
});

export type PaymentMethodSalesOutput = z.infer<typeof PaymentMethodSalesOutputSchema>;
export const StoreSalesOutputSchema = z.object({
  storeId: z.string(),
  storeCode: z.string(),
  name: z.string(),
  totalRevenue: z.string(),
  salesCount: z.coerce.number(),
});

export type StoreSalesOutput = z.infer<typeof StoreSalesOutputSchema>;
export const TopProductOutputSchema = z.object({
  productId: z.string(),
  productCode: z.string(),
  name: z.string(),
  totalRevenue: z.string(),
  unitsSold: z.coerce.number(),
});

export type TopProductOutput = z.infer<typeof TopProductOutputSchema>;
export const DashboardDataSchema = z.object({
  salesOverTime: z.array(DailySalesOutputSchema),
  topProducts: z.array(TopProductOutputSchema),
  inventorySummary: InventorySummaryOutputSchema,
  salesByStore: z.array(StoreSalesOutputSchema),
  salesByPayment: z.array(PaymentMethodSalesOutputSchema),
  periodStart: z.string(),
  periodEnd: z.string(),
});

export type DashboardData = z.infer<typeof DashboardDataSchema>;
export const DashboardInputSchema = z.object({
  storeId: z.string().optional(),
  days: z.coerce.number(),
});

export type DashboardInput = z.infer<typeof DashboardInputSchema>;
export const DateRangeInputSchema = z.object({
  storeId: z.string().optional(),
  start: z.string(),
  end: z.string(),
});

export type DateRangeInput = z.infer<typeof DateRangeInputSchema>;
export const InventoryStatusSchema = z.enum(["IN_STOCK", "LOW_STOCK", "OUT_OF_STOCK"]);

export type InventoryStatus = z.infer<typeof InventoryStatusSchema>;
export const MoneySchema = z.object({
  amount: z.string(),
});

export type Money = z.infer<typeof MoneySchema>;
export const QuantitySchema = z.object({
  value: z.coerce.number(),
});

export type Quantity = z.infer<typeof QuantitySchema>;
export const InventorySchema = z.object({
  id: z.string(),
  inventoryCode: CodeSchema,
  storeId: z.string(),
  productId: z.string(),
  quantity: QuantitySchema,
  priceLocal: MoneySchema,
  minStock: QuantitySchema,
  status: InventoryStatusSchema,
  lastUpdated: z.string(),
  active: z.coerce.boolean(),
});

export type Inventory = z.infer<typeof InventorySchema>;
export const InventoryMovementOutputSchema = z.object({
  movementId: z.string(),
  inventoryId: z.string(),
  movementType: z.string(),
  oldQuantity: z.coerce.number(),
  newQuantity: z.coerce.number(),
  requiresRestock: z.coerce.boolean(),
  isOutOfStock: z.coerce.boolean(),
  description: z.string().optional(),
});

export type InventoryMovementOutput = z.infer<typeof InventoryMovementOutputSchema>;
export const NameSchema = z.object({
  value: TextValueSchema,
});

export type Name = z.infer<typeof NameSchema>;
export const PaymentMethodSchema = z.enum(["Cash", "CreditCard", "BankTransfer", "Other"]);

export type PaymentMethod = z.infer<typeof PaymentMethodSchema>;
export const PhoneNumberSchema = z.object({
  value: z.string(),
});

export type PhoneNumber = z.infer<typeof PhoneNumberSchema>;
export const ProductSchema = z.object({
  id: z.string(),
  productCode: CodeSchema,
  name: NameSchema,
  initialPrice: MoneySchema,
  active: z.coerce.boolean(),
});

export type Product = z.infer<typeof ProductSchema>;
export const PurchaseItemSchema = z.object({
  id: z.string(),
  purchaseId: z.string(),
  inventoryId: z.string(),
  quantity: QuantitySchema,
  unitCost: MoneySchema,
  subtotal: MoneySchema,
});

export type PurchaseItem = z.infer<typeof PurchaseItemSchema>;
export const PurchaseSchema = z.object({
  id: z.string(),
  supplierId: z.string().optional(),
  storeId: z.string(),
  totalCost: MoneySchema,
  purchaseDate: z.string(),
  description: TextValueSchema.optional(),
  purchaseCode: CodeSchema,
  items: z.array(PurchaseItemSchema),
});

export type Purchase = z.infer<typeof PurchaseSchema>;
export const PurchaseItemInputSchema = z.object({
  productId: z.string().min(1, { message: "Product ID is required" }),
  quantity: z.coerce.number().min(1, { message: "Quantity must be at least 1" }),
  unitCost: z.string().min(1, { message: "Unit cost is required" }),
});

export type PurchaseItemInput = z.infer<typeof PurchaseItemInputSchema>;
export const PurchaseOperationOutputSchema = z.object({
  purchaseId: z.string(),
  purchaseCode: z.string(),
  storeId: z.string(),
  supplierId: z.string().optional(),
  totalCost: z.string(),
  purchaseDate: z.string(),
  description: z.string().optional(),
  itemsCount: z.coerce.number(),
  movementsRegistered: z.coerce.number(),
});

export type PurchaseOperationOutput = z.infer<typeof PurchaseOperationOutputSchema>;
export const RegisterPurchaseOperationInputSchema = z.object({
  storeId: z.string().min(1, { message: "Store ID is required" }),
  supplierId: z.string().optional(),
  purchaseCode: z.string().min(1, { message: "Purchase code must be 1-50 chars" }).max(50, { message: "Purchase code must be 1-50 chars" }),
  description: z.string().max(500, { message: "Description must be at most 500 chars" }).optional(),
  items: z.array(PurchaseItemInputSchema).min(1, { message: "Purchase must have at least one item" }),
});

export type RegisterPurchaseOperationInput = z.infer<typeof RegisterPurchaseOperationInputSchema>;
export const RegisterRestockInputSchema = z.object({
  inventoryId: z.string(),
  quantity: z.coerce.number(),
  description: z.string().max(256).optional(),
});

export type RegisterRestockInput = z.infer<typeof RegisterRestockInputSchema>;
export const SaleItemInputSchema = z.object({
  productId: z.string().min(1, { message: "Product ID is required" }),
  quantity: z.coerce.number().min(1, { message: "Quantity must be at least 1" }),
  unitPrice: z.string().min(1, { message: "Unit price is required" }),
});

export type SaleItemInput = z.infer<typeof SaleItemInputSchema>;
export const RegisterSaleOperationInputSchema = z.object({
  storeId: z.string().min(1, { message: "Store ID is required" }),
  saleCode: z.string().min(1, { message: "Sale code must be 1-50 chars" }).max(50, { message: "Sale code must be 1-50 chars" }),
  paymentMethod: z.string().min(1, { message: "Payment method is required" }),
  items: z.array(SaleItemInputSchema).min(1, { message: "Sale must have at least one item" }),
});

export type RegisterSaleOperationInput = z.infer<typeof RegisterSaleOperationInputSchema>;
export const RegisterShrinkageInputSchema = z.object({
  inventoryId: z.string(),
  quantity: z.coerce.number(),
  description: z.string().max(256).optional(),
});

export type RegisterShrinkageInput = z.infer<typeof RegisterShrinkageInputSchema>;
export const SaleItemSchema = z.object({
  id: z.string(),
  saleId: z.string(),
  inventoryId: z.string(),
  quantity: QuantitySchema,
  unitPrice: MoneySchema,
  subtotal: MoneySchema,
});

export type SaleItem = z.infer<typeof SaleItemSchema>;
export const SaleSchema = z.object({
  id: z.string(),
  storeId: z.string(),
  saleCode: CodeSchema,
  total: MoneySchema,
  paymentMethod: PaymentMethodSchema,
  saleDate: z.string(),
  items: z.array(SaleItemSchema),
});

export type Sale = z.infer<typeof SaleSchema>;
export const SaleOperationOutputSchema = z.object({
  saleId: z.string(),
  saleCode: z.string(),
  storeId: z.string(),
  total: z.string(),
  paymentMethod: z.string(),
  saleDate: z.string(),
  itemsCount: z.coerce.number(),
  movementsRegistered: z.coerce.number(),
});

export type SaleOperationOutput = z.infer<typeof SaleOperationOutputSchema>;
export const StoreSchema = z.object({
  id: z.string(),
  storeCode: CodeSchema,
  name: NameSchema,
  address: TextValueSchema,
  phone: PhoneNumberSchema.optional(),
  active: z.coerce.boolean(),
});

export type Store = z.infer<typeof StoreSchema>;
export const SupplierSchema = z.object({
  id: z.string(),
  name: NameSchema,
  supplierCode: CodeSchema,
  contactName: TextValueSchema.optional(),
  phone: PhoneNumberSchema.optional(),
  address: TextValueSchema.optional(),
  active: z.coerce.boolean(),
});

export type Supplier = z.infer<typeof SupplierSchema>;
export const SupplyAgreementSchema = z.object({
  id: z.string(),
  productId: z.string(),
  supplierId: z.string(),
  cost: MoneySchema.optional(),
  active: z.coerce.boolean(),
});

export type SupplyAgreement = z.infer<typeof SupplyAgreementSchema>;
export const TopProductsInputSchema = z.object({
  storeId: z.string().optional(),
  start: z.string(),
  end: z.string(),
  limit: z.coerce.number(),
});

export type TopProductsInput = z.infer<typeof TopProductsInputSchema>;
export const UpdateInventoryInputSchema = z.object({
  inventoryCode: z.string().min(1, { message: "Inventory code must be between 1 and 20 characters" }).max(20, { message: "Inventory code must be between 1 and 20 characters" }).optional(),
  storeId: z.string().optional(),
  productId: z.string().optional(),
  quantity: z.coerce.number().optional(),
  priceLocal: z.string().optional(),
  minStock: z.coerce.number().optional(),
  status: z.string().min(1, { message: "Status cannot be empty" }).optional(),
  active: z.coerce.boolean().optional(),
});

export type UpdateInventoryInput = z.infer<typeof UpdateInventoryInputSchema>;
export const UpdateProductInputSchema = z.object({
  productCode: z.string().min(1, { message: "Product code must be between 1 and 20 characters" }).max(20, { message: "Product code must be between 1 and 20 characters" }).optional(),
  name: z.string().min(1, { message: "Name must be between 1 and 100 characters" }).max(100, { message: "Name must be between 1 and 100 characters" }).optional(),
  initialPrice: z.string().optional(),
  active: z.coerce.boolean().optional(),
});

export type UpdateProductInput = z.infer<typeof UpdateProductInputSchema>;
export const UpdateStoreInputSchema = z.object({
  storeCode: z.string().min(1, { message: "Store code must be between 1 and 20 characters" }).max(20, { message: "Store code must be between 1 and 20 characters" }).optional(),
  name: z.string().min(1, { message: "Name must be between 1 and 100 characters" }).max(100, { message: "Name must be between 1 and 100 characters" }).optional(),
  address: z.string().min(1, { message: "Address cannot be empty" }).optional(),
  phone: z.string().min(7, { message: "Phone number length is invalid" }).max(20, { message: "Phone number length is invalid" }).optional().optional(),
  active: z.coerce.boolean().optional(),
});

export type UpdateStoreInput = z.infer<typeof UpdateStoreInputSchema>;
export const UpdateSupplierInputSchema = z.object({
  name: z.string().min(1, { message: "Name must be between 1 and 100 characters" }).max(100, { message: "Name must be between 1 and 100 characters" }).optional(),
  supplierCode: z.string().min(1, { message: "Supplier code must be between 1 and 20 characters" }).max(20, { message: "Supplier code must be between 1 and 20 characters" }).optional(),
  contactName: z.string().min(1, { message: "Contact name cannot be empty" }).optional().optional(),
  phone: z.string().min(7, { message: "Phone number length is invalid" }).max(20, { message: "Phone number length is invalid" }).optional().optional(),
  address: z.string().min(1, { message: "Address cannot be empty" }).optional().optional(),
  active: z.coerce.boolean().optional(),
});

export type UpdateSupplierInput = z.infer<typeof UpdateSupplierInputSchema>;
export const UpdateSupplyAgreementInputSchema = z.object({
  productId: z.string().optional(),
  supplierId: z.string().optional(),
  cost: z.string().optional().optional(),
  active: z.coerce.boolean().optional(),
});

export type UpdateSupplyAgreementInput = z.infer<typeof UpdateSupplyAgreementInputSchema>;
export const CreateInventoryParamsSchema = z.object({
  input: CreateInventoryInputSchema,
});

export const CreateProductParamsSchema = z.object({
  input: CreateProductInputSchema,
});

export const CreateStoreParamsSchema = z.object({
  input: CreateStoreInputSchema,
});

export const CreateSupplierParamsSchema = z.object({
  input: CreateSupplierInputSchema,
});

export const CreateSupplyAgreementParamsSchema = z.object({
  input: CreateSupplyAgreementInputSchema,
});

export const DeleteInventoryParamsSchema = z.object({
  id: z.string(),
});

export const DeleteProductParamsSchema = z.object({
  id: z.string(),
});

export const DeleteStoreParamsSchema = z.object({
  id: z.string(),
});

export const DeleteSupplierParamsSchema = z.object({
  id: z.string(),
});

export const DeleteSupplyAgreementParamsSchema = z.object({
  id: z.string(),
});

export const FindPurchaseByIdParamsSchema = z.object({
  id: z.string(),
});

export const FindSaleByIdParamsSchema = z.object({
  id: z.string(),
});

export const GetDashboardDataParamsSchema = z.object({
  input: DashboardInputSchema,
});

export const GetInventorySummaryParamsSchema = z.object({
  storeId: z.string().optional().optional(),
});

export const GetSalesByPaymentMethodParamsSchema = z.object({
  input: DateRangeInputSchema,
});

export const GetSalesByStoreParamsSchema = z.object({
  input: DateRangeInputSchema,
});

export const GetSalesOverTimeParamsSchema = z.object({
  input: DateRangeInputSchema,
});

export const GetTopProductsParamsSchema = z.object({
  input: TopProductsInputSchema,
});

export const RegisterPurchaseOperationParamsSchema = z.object({
  input: RegisterPurchaseOperationInputSchema,
});

export const RegisterRestockMovementParamsSchema = z.object({
  input: RegisterRestockInputSchema,
});

export const RegisterSaleOperationParamsSchema = z.object({
  input: RegisterSaleOperationInputSchema,
});

export const RegisterShrinkageMovementParamsSchema = z.object({
  input: RegisterShrinkageInputSchema,
});

export const SearchInventoriesParamsSchema = z.object({
  input: CriteriaInputSchema,
});

export const SearchProductsParamsSchema = z.object({
  input: CriteriaInputSchema,
});

export const SearchPurchasesParamsSchema = z.object({
  input: CriteriaInputSchema,
});

export const SearchSalesParamsSchema = z.object({
  input: CriteriaInputSchema,
});

export const SearchStoresParamsSchema = z.object({
  input: CriteriaInputSchema,
});

export const SearchSuppliersParamsSchema = z.object({
  input: CriteriaInputSchema,
});

export const SearchSupplyAgreementsParamsSchema = z.object({
  input: CriteriaInputSchema,
});

export const UpdateInventoryParamsSchema = z.object({
  id: z.string(),
  input: UpdateInventoryInputSchema,
});

export const UpdateProductParamsSchema = z.object({
  id: z.string(),
  input: UpdateProductInputSchema,
});

export const UpdateStoreParamsSchema = z.object({
  id: z.string(),
  input: UpdateStoreInputSchema,
});

export const UpdateSupplierParamsSchema = z.object({
  id: z.string(),
  input: UpdateSupplierInputSchema,
});

export const UpdateSupplyAgreementParamsSchema = z.object({
  id: z.string(),
  input: UpdateSupplyAgreementInputSchema,
});


export type CreateInventoryParams = z.infer<typeof CreateInventoryParamsSchema>;



export type CreateProductParams = z.infer<typeof CreateProductParamsSchema>;



export type CreateStoreParams = z.infer<typeof CreateStoreParamsSchema>;



export type CreateSupplierParams = z.infer<typeof CreateSupplierParamsSchema>;



export type CreateSupplyAgreementParams = z.infer<typeof CreateSupplyAgreementParamsSchema>;



export type DeleteInventoryParams = z.infer<typeof DeleteInventoryParamsSchema>;



export type DeleteProductParams = z.infer<typeof DeleteProductParamsSchema>;



export type DeleteStoreParams = z.infer<typeof DeleteStoreParamsSchema>;



export type DeleteSupplierParams = z.infer<typeof DeleteSupplierParamsSchema>;



export type DeleteSupplyAgreementParams = z.infer<typeof DeleteSupplyAgreementParamsSchema>;



export type FindPurchaseByIdParams = z.infer<typeof FindPurchaseByIdParamsSchema>;



export type FindSaleByIdParams = z.infer<typeof FindSaleByIdParamsSchema>;



export type GetDashboardDataParams = z.infer<typeof GetDashboardDataParamsSchema>;



export type GetInventorySummaryParams = z.infer<typeof GetInventorySummaryParamsSchema>;



export type GetSalesByPaymentMethodParams = z.infer<typeof GetSalesByPaymentMethodParamsSchema>;



export type GetSalesByStoreParams = z.infer<typeof GetSalesByStoreParamsSchema>;



export type GetSalesOverTimeParams = z.infer<typeof GetSalesOverTimeParamsSchema>;



export type GetTopProductsParams = z.infer<typeof GetTopProductsParamsSchema>;



export type RegisterPurchaseOperationParams = z.infer<typeof RegisterPurchaseOperationParamsSchema>;



export type RegisterRestockMovementParams = z.infer<typeof RegisterRestockMovementParamsSchema>;



export type RegisterSaleOperationParams = z.infer<typeof RegisterSaleOperationParamsSchema>;



export type RegisterShrinkageMovementParams = z.infer<typeof RegisterShrinkageMovementParamsSchema>;



export type SearchInventoriesParams = z.infer<typeof SearchInventoriesParamsSchema>;



export type SearchProductsParams = z.infer<typeof SearchProductsParamsSchema>;



export type SearchPurchasesParams = z.infer<typeof SearchPurchasesParamsSchema>;



export type SearchSalesParams = z.infer<typeof SearchSalesParamsSchema>;



export type SearchStoresParams = z.infer<typeof SearchStoresParamsSchema>;



export type SearchSuppliersParams = z.infer<typeof SearchSuppliersParamsSchema>;



export type SearchSupplyAgreementsParams = z.infer<typeof SearchSupplyAgreementsParamsSchema>;



export type UpdateInventoryParams = z.infer<typeof UpdateInventoryParamsSchema>;



export type UpdateProductParams = z.infer<typeof UpdateProductParamsSchema>;



export type UpdateStoreParams = z.infer<typeof UpdateStoreParamsSchema>;



export type UpdateSupplierParams = z.infer<typeof UpdateSupplierParamsSchema>;



export type UpdateSupplyAgreementParams = z.infer<typeof UpdateSupplyAgreementParamsSchema>;


